### PR TITLE
test(lex): fix static check warning literalloopclosure

### PR DESCRIPTION
**Pull request by bluebrown**
fixes `loop variable tc captured by func literalloopclosure`

### CODE REVIEW

**Comment by jimlambrt** [comment]
I took the liberty of pushing a fixup commit that fixes all the other occurrences of this.

**Review by jimlambrt — APPROVED** [review]
ty!

**Comment by bluebrown** [comment]
ah sorry, for not handling all of them. I toolchain was only marking that one with a warning.

**Comment by jimlambrt** [comment]
No worries!  I appreciate the contribution.

**Pull request merged**
